### ISSUE TITLE
layout borken when give [verticalLineClassNamesForTime] prop && zoomOut

### ISSUE THREAD

**Issue by SuperWallaby** [namespace-ee/react-calendar-timeline#532]
**Describe the bug**
loayout broken when i give  [verticalLineClassNamesForTime] porp
```jsx 
<Timeline
          {...otherProps}
          verticalLineClassNamesForTime={(timeStart, timeEnd) => {
          // remove next line then, everyThing is Ok
            if (timeStart < new Date().getTime()) return ['verticalLine','verticalLine--past'];
            return ['verticalLine']
          }
          }
          horizontalLineClassNamesForGroup={group => ['group']}
        />
```

**Screenshots**
## ZOOM IN
![ok in here](https://user-images.githubusercontent.com/46065365/53806069-490d6a80-3f8f-11e9-8d2d-2721c515c494.png)
## ZOOM OUT
![cssout](https://user-images.githubusercontent.com/46065365/53806645-d3a29980-3f90-11e9-9d27-e8a12ff755a5.png)

**Library Version**
"react": "^16.7.0",
"react-calendar-timeline": "^0.23.0",

**Desktop (please complete the following information):**
* Browser chrom 
* Version 72.0.3626.119

**Additional context**
I did not give any css or js about  verticalLine && verticalLine--past classes  can make problem
and that is only happen when zoomOut at least month view  

I am finding what happen to here  
when i am find i will update

**Comment by Ilaiwi** [comment]
I tried reproducing this [here](https://codesandbox.io/s/r71390k11m) no luck though please provide a codesandbox example so I can help you

**Comment by SuperWallaby** [comment]
oh sorry
next time i will

**Comment by Ilaiwi** [comment]
no reproduce example was provided I will close this

**Comment by kevinhury** [comment]
@Ilaiwi I was able to reproduce the bug with the codesandbox you provided [here](https://github.com/namespace-ee/react-calendar-timeline/issues/532#issuecomment-470027551)

Please zoom to the point the header unit type is month. See this screenshot from your sandbox:
<img width="927" alt="Screen Shot 2019-11-13 at 15 43 02" src="https://user-images.githubusercontent.com/5544095/68769051-5a356d80-062c-11ea-9d19-09907ca7c8e4.png">

**Comment by Ilaiwi** [comment]
should be fixed when #673 lands

**Comment by kevinhury** [comment]
@Ilaiwi Thanks! when is the next release?

**Comment by Ilaiwi** [comment]
@kevinhury sorry I don't have an ETA for the rowRenderer feature yet

**Comment by rosanzheng** [comment]
@SuperWallaby - Have you found a solution to your problem? I am still facing the same problem here.

**Comment by marchiartur** [comment]
> @SuperWallaby - Have you found a solution to your problem? I am still facing the same problem here.

+1
