### ISSUE TITLE
Unable to load time line data until we minimize and maximize the browser

### ISSUE THREAD

**Issue by MkrishnaPodshore** [namespace-ee/react-calendar-timeline#688]
Implemented the timeline chart, but unable to view the chart data until we minimize and maximize the browser.

![image](https://user-images.githubusercontent.com/55871137/69367542-7f764b80-0cbe-11ea-8654-f590c899a165.png)

**Comment by ApexWeed** [comment]
Experienced the same behaviour on 0.26.7. Seems to only happen if the timeline is first rendered with an empty item list as my items are loaded are loaded from an async effect. Changing it to render a blank div instead if there are no items fixed it for me.

**Comment by Ilaiwi** [comment]
this should be fixed in `beta` version. try it out with `@beta` and lmk if this worked for you.

**Comment by diegocasmo** [comment]
I had the same issue and rendering a blank blank div wasn't an option for me. Instead, I fire a `resize` event which forces the timeline to re-compute the dates (I know, this is hacky...):

``` jsx
import RCTimeline from 'react-calendar-timeline';

class MyComponent extends PureComponent {
  componentDidUpdate(prevProps) {
    this.forceResize(prevProps);
  }

  forceResize(prevProps) {
    if (prevProps.items.length > 0) return;
    if (this.props.items.length === 0) return;

    window.dispatchEvent(new Event('resize'));
  }

  render() {
    const { groups, items } = this.props;

    return (
      <RCTimeline groups={groups} items={items}/>
    );
  }
}
```

**Comment by THPubs** [comment]
For me also it worked only after running `window.dispatchEvent(new Event('resize'));`. @Ilaiwi any idea what's happening?

**Comment by Ilaiwi** [comment]
@THPubs please try the beta

**Comment by THPubs** [comment]
@Ilaiwi Already using the latest beta `0.27.3-beta`. Still facing the issue.

**Comment by janakact** [comment]
Facing the same issue. This works as a temporary fix. `window.dispatchEvent(new Event('resize'));`

**Comment by maormagori** [comment]
This bug still occurs .` window.dispatchEvent(new Event('resize'));` still does the job,
